name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up openJDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew clean build
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.1
        env:
          CC_TEST_REPORTER_ID: ${{secrets.SEKRETIK}}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco